/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnalyzeHome: typeof import('./src/components/analyze/AnalyzeHome.vue')['default']
    BuildVariableGroups: typeof import('./src/components/analyze/BuildVariableGroups.vue')['default']
    ConvertFromGridwareFormat: typeof import('./src/components/convert/ConvertFromGridwareFormat.vue')['default']
    ConvertToGridwareFormat: typeof import('./src/components/convert/ConvertToGridwareFormat.vue')['default']
    EncodingSelector: typeof import('./src/components/widgets/EncodingSelector.vue')['default']
    FilterVariables: typeof import('./src/components/analyze/FilterVariables.vue')['default']
    GridWareHome: typeof import('./src/components/GridWareHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableViewer: typeof import('./src/components/widgets/TableViewer.vue')['default']
    VariableGroupBuilder: typeof import('./src/components/widgets/VariableGroupBuilder.vue')['default']
    VariableGroupRow: typeof import('./src/components/widgets/VariableGroupRow.vue')['default']
    VariableSettingPanel: typeof import('./src/components/widgets/VariableSettingPanel.vue')['default']
  }
}
